name:                voskell
version:             0.1.0.0
github:              "troussil/voskell"
license:             BSD3
author:              "Tristan Roussillon"
maintainer:          "tristan.roussillon@liris.cnrs.fr"
copyright:           "Copyright (c) 2019 Tristan Roussillon"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Digital geometry

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/yourusername/voskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  voskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - voskell

tests:
  voskell-tests:
    main: Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - voskell
    - QuickCheck
